// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric820

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void imgLoading_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_scrbooting
void ui_scrbooting_screen_init(void);
void ui_event_scrbooting(lv_event_t * e);
lv_obj_t * ui_scrbooting;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label78;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES
lv_obj_t * uic_scrbooting;

// SCREEN: ui_scrmain
void ui_scrmain_screen_init(void);
void ui_event_scrmain(lv_event_t * e);
lv_obj_t * ui_scrmain;
void ui_event_TabView1(lv_event_t * e);
lv_obj_t * ui_TabView1;
lv_obj_t * ui_Tab1;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label77;
lv_obj_t * ui_Label80;
lv_obj_t * ui_Label81;
lv_obj_t * ui_Label82;
lv_obj_t * ui_Label83;
lv_obj_t * ui_chartKV;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label88;
lv_obj_t * ui_Label79;
lv_obj_t * ui_Label84;
lv_obj_t * ui_Label85;
lv_obj_t * ui_Label86;
lv_obj_t * ui_chartKV2;
void ui_event_Label153(lv_event_t * e);
lv_obj_t * ui_Label153;
lv_obj_t * ui_Tab2;
void ui_event_TabView2(lv_event_t * e);
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPage13;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label53;
void ui_event_passtextarea(lv_event_t * e);
lv_obj_t * ui_passtextarea;
lv_obj_t * ui_Label57;
void ui_event_yeartextarea(lv_event_t * e);
lv_obj_t * ui_yeartextarea;
void ui_event_monthtextarea(lv_event_t * e);
lv_obj_t * ui_monthtextarea;
void ui_event_daytextarea(lv_event_t * e);
lv_obj_t * ui_daytextarea;
void ui_event_hourtextarea(lv_event_t * e);
lv_obj_t * ui_hourtextarea;
void ui_event_mintextarea(lv_event_t * e);
lv_obj_t * ui_mintextarea;
void ui_event_secondtextarea(lv_event_t * e);
lv_obj_t * ui_secondtextarea;
lv_obj_t * ui_key13;
lv_obj_t * ui_Label95;
void ui_event_Keyboard4(lv_event_t * e);
lv_obj_t * ui_Keyboard4;
lv_obj_t * ui_TabPage17;
lv_obj_t * ui_Panel73;
lv_obj_t * ui_Label76;
void ui_event_backlighttextarea2(lv_event_t * e);
lv_obj_t * ui_backlighttextarea2;
void ui_event_passtextarea2(lv_event_t * e);
lv_obj_t * ui_passtextarea2;
lv_obj_t * ui_Label91;
lv_obj_t * ui_Label93;
lv_obj_t * ui_Label175;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label8;
lv_obj_t * ui_key4;
lv_obj_t * ui_Label178;
void ui_event_Keyboard5(lv_event_t * e);
lv_obj_t * ui_Keyboard5;
lv_obj_t * ui_TabPage8;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
void ui_event_pttextarea(lv_event_t * e);
lv_obj_t * ui_pttextarea;
void ui_event_cttextarea(lv_event_t * e);
lv_obj_t * ui_cttextarea;
lv_obj_t * ui_Label33;
void ui_event_i0overtextarea(lv_event_t * e);
lv_obj_t * ui_i0overtextarea;
lv_obj_t * ui_Label149;
void ui_event_i0overtextarea2(lv_event_t * e);
lv_obj_t * ui_i0overtextarea2;
lv_obj_t * ui_key6;
lv_obj_t * ui_Label35;
void ui_event_Keyboard8(lv_event_t * e);
lv_obj_t * ui_Keyboard8;
lv_obj_t * ui_TabPage12;
lv_obj_t * ui_Label66;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Label69;
lv_obj_t * ui_Label70;
lv_obj_t * ui_Label71;
lv_obj_t * ui_Label72;
lv_obj_t * ui_Label73;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label7;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label4;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label2;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label5;
lv_obj_t * ui_TabPage10;
lv_obj_t * ui_Label150;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label151;
void ui_event_abcovertextarea2(lv_event_t * e);
lv_obj_t * ui_abcovertextarea2;
void ui_event_abcovertextarea(lv_event_t * e);
lv_obj_t * ui_abcovertextarea;
void ui_event_abcdroptextarea3(lv_event_t * e);
lv_obj_t * ui_abcdroptextarea3;
lv_obj_t * ui_key3;
lv_obj_t * ui_Label59;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_TabPage6;
lv_obj_t * ui_TabView4;
lv_obj_t * ui_TabPage5;
lv_obj_t * ui_Panel14;
void ui_event_TextArea7(lv_event_t * e);
lv_obj_t * ui_TextArea7;
void ui_event_Dropdown1(lv_event_t * e);
lv_obj_t * ui_Dropdown1;
void ui_event_TextArea8(lv_event_t * e);
lv_obj_t * ui_TextArea8;
void ui_event_TextArea9(lv_event_t * e);
lv_obj_t * ui_TextArea9;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label90;
void ui_event_TextArea16(lv_event_t * e);
lv_obj_t * ui_TextArea16;
lv_obj_t * ui_key8;
lv_obj_t * ui_Label25;
void ui_event_Keyboard10(lv_event_t * e);
lv_obj_t * ui_Keyboard10;
lv_obj_t * ui_TabPage14;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label19;
void ui_event_Checkbox2(lv_event_t * e);
lv_obj_t * ui_Checkbox2;
void ui_event_Checkbox1(lv_event_t * e);
lv_obj_t * ui_Checkbox1;
lv_obj_t * ui_Panel1;
void ui_event_TextArea10(lv_event_t * e);
lv_obj_t * ui_TextArea10;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
void ui_event_TextArea11(lv_event_t * e);
lv_obj_t * ui_TextArea11;
void ui_event_TextArea12(lv_event_t * e);
lv_obj_t * ui_TextArea12;
void ui_event_TextArea13(lv_event_t * e);
lv_obj_t * ui_TextArea13;
lv_obj_t * ui_key9;
lv_obj_t * ui_Label27;
void ui_event_Keyboard11(lv_event_t * e);
lv_obj_t * ui_Keyboard11;
lv_obj_t * ui_TabPage11;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Label46;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label47;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label48;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label49;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label50;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label51;
lv_obj_t * ui_paddialog;
void ui_event_pttextarea2(lv_event_t * e);
lv_obj_t * ui_pttextarea2;
lv_obj_t * ui_Label89;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_key10;
lv_obj_t * ui_Label179;
void ui_event_Keyboard6(lv_event_t * e);
lv_obj_t * ui_Keyboard6;
lv_obj_t * ui_Tab3;
void ui_event_TabView3(lv_event_t * e);
lv_obj_t * ui_TabView3;
lv_obj_t * ui_Tab3nav1;
lv_obj_t * ui_Panel62;
lv_obj_t * ui_tool2;
void ui_event_Button24(lv_event_t * e);
lv_obj_t * ui_Button24;
lv_obj_t * ui_Label154;
lv_obj_t * ui_Label159;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label157;
lv_obj_t * ui_Tab3nav2;
lv_obj_t * ui_Panel63;
lv_obj_t * ui_tool3;
void ui_event_Button23(lv_event_t * e);
lv_obj_t * ui_Button23;
lv_obj_t * ui_Label161;
lv_obj_t * ui_Label137;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label141;
void ui_event_Reset2(lv_event_t * e);
lv_obj_t * ui_Reset2;
lv_obj_t * ui_Label158;
lv_obj_t * ui_Tab3nav4;
lv_obj_t * ui_Panel65;
lv_obj_t * ui_tool5;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label142;
lv_obj_t * ui_Label143;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label144;
void ui_event_Reset4(lv_event_t * e);
lv_obj_t * ui_Reset4;
lv_obj_t * ui_Label162;
lv_obj_t * ui_Tab3nav5;
lv_obj_t * ui_Panel66;
lv_obj_t * ui_tool6;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label164;
lv_obj_t * ui_Label145;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label146;
void ui_event_Reset5(lv_event_t * e);
lv_obj_t * ui_Reset5;
lv_obj_t * ui_Label160;
lv_obj_t * ui_Tab3nav6;
lv_obj_t * ui_Panel67;
lv_obj_t * ui_tool7;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
lv_obj_t * ui_Label147;
lv_obj_t * ui_Label148;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label165;
void ui_event_Reset6(lv_event_t * e);
lv_obj_t * ui_Reset6;
lv_obj_t * ui_Label166;
lv_obj_t * ui_Panel70;
lv_obj_t * ui_Panel68;
lv_obj_t * ui_Label171;
lv_obj_t * ui_Label163;
lv_obj_t * ui_Label167;
lv_obj_t * ui_Label168;
lv_obj_t * ui_Label169;
lv_obj_t * ui_chartKV4;
lv_obj_t * ui_Panel72;
lv_obj_t * ui_Panel69;
lv_obj_t * ui_Label176;
lv_obj_t * ui_Label170;
lv_obj_t * ui_Label172;
lv_obj_t * ui_Label173;
lv_obj_t * ui_Label174;
lv_obj_t * ui_chartKV5;
lv_obj_t * ui_Label177;
lv_obj_t * ui_Label87;
lv_obj_t * ui_Label180;
lv_obj_t * ui_Tab4;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Label99;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label100;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Label102;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Label106;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Label98;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Label103;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_Label104;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Label110;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Label105;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_Label107;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_Label108;
lv_obj_t * ui_Panel36;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_Label114;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Label109;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_Label111;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Label112;
lv_obj_t * ui_Panel37;
lv_obj_t * ui_Panel38;
lv_obj_t * ui_Label115;
lv_obj_t * ui_Panel39;
lv_obj_t * ui_Label116;
lv_obj_t * ui_Panel40;
lv_obj_t * ui_Label117;
lv_obj_t * ui_Panel41;
lv_obj_t * ui_Label118;
lv_obj_t * ui_Panel42;
lv_obj_t * ui_Panel43;
lv_obj_t * ui_Label119;
lv_obj_t * ui_Panel44;
lv_obj_t * ui_Label120;
lv_obj_t * ui_Panel45;
lv_obj_t * ui_Label121;
lv_obj_t * ui_Panel46;
lv_obj_t * ui_Label122;
lv_obj_t * ui_Panel47;
lv_obj_t * ui_Panel48;
lv_obj_t * ui_Label123;
lv_obj_t * ui_Panel49;
lv_obj_t * ui_Label124;
lv_obj_t * ui_Panel50;
lv_obj_t * ui_Label125;
lv_obj_t * ui_Panel51;
lv_obj_t * ui_Label126;
lv_obj_t * ui_Panel52;
lv_obj_t * ui_Panel53;
lv_obj_t * ui_Label127;
lv_obj_t * ui_Panel54;
lv_obj_t * ui_Label128;
lv_obj_t * ui_Panel55;
lv_obj_t * ui_Label129;
lv_obj_t * ui_Panel56;
lv_obj_t * ui_Label130;
lv_obj_t * ui_Panel57;
lv_obj_t * ui_Panel58;
lv_obj_t * ui_Label131;
lv_obj_t * ui_Panel59;
lv_obj_t * ui_Label132;
lv_obj_t * ui_Panel60;
lv_obj_t * ui_Label133;
lv_obj_t * ui_Panel61;
lv_obj_t * ui_Label134;
lv_obj_t * ui_tool;
lv_obj_t * ui_Label113;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label156;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label155;
lv_obj_t * ui_Tab5;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label74;
lv_obj_t * ui_Label75;
lv_obj_t * ui_Label94;
lv_obj_t * ui_Label96;
lv_obj_t * ui_Label97;
lv_obj_t * ui_dialog;
lv_obj_t * ui_Label152;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label60;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label139;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label39;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void imgLoading_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -300, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_scrbooting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_scrmain, LV_SCR_LOAD_ANIM_FADE_ON, 400, 800, &ui_scrmain_screen_init);
    }
}

void ui_event_scrmain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        scrmainloaded(e);
    }
}

void ui_event_TabView1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        settingstabchanged(e);
    }
}

void ui_event_Label153(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_paddialog, LV_OBJ_FLAG_FLOATING, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TabView2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        settingstabchanged(e);
    }
}

void ui_event_passtextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_passtextarea);
    }
}

void ui_event_yeartextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_yeartextarea);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        timechanged(e);
    }
}

void ui_event_monthtextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_monthtextarea);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        timechanged(e);
    }
}

void ui_event_daytextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_daytextarea);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        timechanged(e);
    }
}

void ui_event_hourtextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_hourtextarea);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        timechanged(e);
    }
}

void ui_event_mintextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_mintextarea);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        timechanged(e);
    }
}

void ui_event_secondtextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard4,  ui_secondtextarea);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        timechanged(e);
    }
}

void ui_event_Keyboard4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_backlighttextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard5,  ui_backlighttextarea2);
    }
}

void ui_event_passtextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard5,  ui_passtextarea2);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touchrecalc(e);
    }
}

void ui_event_Keyboard5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_pttextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_pttextarea);
    }
}

void ui_event_cttextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_cttextarea);
    }
}

void ui_event_i0overtextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_i0overtextarea);
    }
}

void ui_event_i0overtextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard8,  ui_i0overtextarea2);
    }
}

void ui_event_Keyboard8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}
void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        preparecal(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        dovoltagecal(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        docurrentcal(e);
    }
}
void ui_event_abcovertextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_abcovertextarea2);
    }
}

void ui_event_abcovertextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_abcovertextarea);
    }
}

void ui_event_abcdroptextarea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_abcdroptextarea3);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_TextArea7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard10,  ui_TextArea7);
    }
}

void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        (e);
    }
}

void ui_event_TextArea8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard10,  ui_TextArea8);
    }
}

void ui_event_TextArea9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard10,  ui_TextArea9);
    }
}

void ui_event_TextArea16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard10,  ui_TextArea16);
    }
}

void ui_event_Keyboard10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_Checkbox2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Checkbox1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_key9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Checkbox1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Checkbox2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_key9, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextArea10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard11,  ui_TextArea10);
    }
}

void ui_event_TextArea11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard11,  ui_TextArea11);
    }
}

void ui_event_TextArea12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard11,  ui_TextArea12);
    }
}

void ui_event_TextArea13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard11,  ui_TextArea13);
    }
}

void ui_event_Keyboard11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        out1clicked(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        out5clicked(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        out4clicked(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        out3clicked(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        out2clicked(e);
    }
}

void ui_event_pttextarea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard6,  ui_pttextarea2);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        checkpassword(e);
    }
}

void ui_event_Keyboard6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ta_event_cb(e);
    }
}

void ui_event_TabView3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        errorpagechanged(e);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        overerrornext(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        overerrorprev(e);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        gnderrornext(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        gnderrorprev(e);
    }
}

void ui_event_Reset2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        errorreset(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        droperrornext(e);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        droperrorprev(e);
    }
}

void ui_event_Reset4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        aclosebtnclicked(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pterrornext(e);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pterrorprev(e);
    }
}

void ui_event_Reset5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        aclosebtnclicked(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        shorterrornext(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        shorterrorprev(e);
    }
}

void ui_event_Reset6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        aclosebtnclicked(e);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        nodelistnext(e);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        nodelistprev(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_dialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        popcancel(e);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        popconform(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrbooting_screen_init();
    ui_scrmain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrbooting);
}
