// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric820

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void scrmainloaded(lv_event_t * e);
void settingstabchanged(lv_event_t * e);
void timechanged(lv_event_t * e);
void ta_event_cb(lv_event_t * e);
void touchrecalc(lv_event_t * e);
void preparecal(lv_event_t * e);
void dovoltagecal(lv_event_t * e);
void docurrentcal(lv_event_t * e);
void out1clicked(lv_event_t * e);
void out5clicked(lv_event_t * e);
void out4clicked(lv_event_t * e);
void out3clicked(lv_event_t * e);
void out2clicked(lv_event_t * e);
void checkpassword(lv_event_t * e);
void errorpagechanged(lv_event_t * e);
void overerrornext(lv_event_t * e);
void overerrorprev(lv_event_t * e);
void gnderrornext(lv_event_t * e);
void gnderrorprev(lv_event_t * e);
void errorreset(lv_event_t * e);
void droperrornext(lv_event_t * e);
void droperrorprev(lv_event_t * e);

void pterrornext(lv_event_t * e);
void pterrorprev(lv_event_t * e);
void shorterrornext(lv_event_t * e);
void shorterrorprev(lv_event_t * e);
void nodelistnext(lv_event_t * e);
void nodelistprev(lv_event_t * e);
void popcancel(lv_event_t * e);
void popconform(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
