// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: eric820
#include "main.h"
#include "ui.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>

extern SETTINGS settings;
extern void nvs_clear_coeff(void);
extern volatile uint8_t save_settings_req;
extern volatile uint8_t save_request_reset;
extern volatile uint8_t save_ptct_req;
extern volatile uint8_t save_vset_req;
extern volatile uint8_t cmd_calc_prepare_req;
extern volatile uint8_t cmd_calc_v_done_req;
extern volatile uint8_t cmd_calc_c_done_req;
extern CALC_STATUS calc_status;
extern volatile uint8_t relay_op_req;
extern volatile uint8_t line_error;
extern volatile uint8_t line_gnd;
extern volatile uint8_t perm_error_clr_req;
extern volatile uint8_t last_error_is_perm;
extern lv_obj_t * nodelist_table[8][4];
extern volatile uint8_t disp_node_page_idx;
extern volatile uint8_t disp_node_page_cnt;
extern volatile uint8_t disp_node_page_update;
extern volatile uint8_t settings_upload_req;
extern volatile uint8_t gnd_error_wave_load;
extern volatile uint8_t over_error_wave_load;
extern volatile uint8_t drop_error_wave_load;
extern volatile uint8_t pt_error_wave_load;
extern volatile uint8_t short_error_wave_load;
volatile uint8_t time_setting_changed = 0;
volatile uint8_t time_settings_auto_update = 1;
extern uint8_t gnd_error_idx;
extern uint8_t gnd_error_cnt;
extern uint8_t over_error_idx;
extern uint8_t over_error_cnt;
extern uint8_t drop_error_idx;
extern uint8_t drop_error_cnt;
extern uint8_t pt_error_idx;
extern uint8_t pt_error_cnt;
extern uint8_t short_error_idx;
extern uint8_t short_error_cnt;

void calcprepare(lv_event_t * e)
{
	// Your code here
}

void calcstart(lv_event_t * e)
{
	// Your code here
}

void saveptandctbtnclicked(lv_event_t * e)
{
	// Your code here
}

void savei0overbtnclicked(lv_event_t * e)
{
	// Your code here
}

void saveptoverbtnclicked(lv_event_t * e)
{
	// Your code here
}

void aclosebtnclicked(lv_event_t * e)
{
	// Your code here
}

void eclosebtnclicked(lv_event_t * e)
{
	// Your code here
}

void dclosebtnclicked(lv_event_t * e)
{
	// Your code here
}

void cclosebtnclicked(lv_event_t * e)
{
	// Your code here
}

void bclosebtnclicked(lv_event_t * e)
{
	// Your code here
}

void savegensettingbtnclick(lv_event_t * e)
{
	// Your code here
}

void pttextareafocused(lv_event_t * e)
{
	// Your code here
}

void cttextareafocused(lv_event_t * e)
{
	// Your code here
}

void i0overtextareafocused(lv_event_t * e)
{
	// Your code here
}

void abcovertextareafocused(lv_event_t * e)
{
	// Your code here
}

void abcdroptextareafocused(lv_event_t * e)
{
	// Your code here
}

void u0overtextareafocused(lv_event_t * e)
{
	// Your code here
}

void passtextareafocused(lv_event_t * e)
{
	// Your code here
}

void backlighttextareafocused(lv_event_t * e)
{
	// Your code here
}

void yeartextareafocused(lv_event_t * e)
{
	// Your code here
}

void monthtextareafocused(lv_event_t * e)
{
	// Your code here
}

void daytextareafocused(lv_event_t * e)
{
	// Your code here
}

void hourtextareafocused(lv_event_t * e)
{
	// Your code here
}

void mintextareafocused(lv_event_t * e)
{
	// Your code here
}

void secondtextareafocused(lv_event_t * e)
{
	// Your code here
}

void ta_event_cb(lv_event_t * e)
{
	// Your code here
	char str[16] = {0};
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * obj = lv_event_get_target(e);
	if(code == LV_EVENT_VALUE_CHANGED) {
			uint32_t id = lv_btnmatrix_get_selected_btn(obj);
			const char * txt = lv_btnmatrix_get_btn_text(obj, id);
			if((ui_Keyboard2 == obj)&&(id == 7))
			{
				rt_kprintf("kb2 ok pressed\n");
				settings.v_over = atoi(lv_textarea_get_text(ui_abcovertextarea2));
				if(settings.v_over < 1)
					settings.v_over = 1;
				else if(settings.v_over >100)
					settings.v_over = 100;
				sprintf(str, "%d", settings.v_over);
				lv_textarea_set_text(ui_abcovertextarea2, str);
				
				settings.v_drop = atoi(lv_textarea_get_text(ui_abcovertextarea));
				if(settings.v_drop < 1)
					settings.v_drop = 1;
				else if(settings.v_drop >200)
					settings.v_drop = 200;
				sprintf(str, "%d", settings.v_drop);
				lv_textarea_set_text(ui_abcovertextarea, str);
				
				settings.u0_limt = atoi(lv_textarea_get_text(ui_abcdroptextarea3));
				if(settings.u0_limt < 1)
					settings.u0_limt = 1;
				else if(settings.u0_limt >100)
					settings.u0_limt = 100;
				sprintf(str, "%d", settings.u0_limt);
				lv_textarea_set_text(ui_abcdroptextarea3, str);
				save_settings_req = 1;
				save_vset_req = 1;
				settings_upload_req = 1;
			}
			else if((ui_Keyboard4 == obj)&&(id == 7))
			{
				rt_kprintf("kb4 ok pressed\n");
				if(time_setting_changed == 1)
				{
					time_setting_changed = 0;
					struct tm timeinfo = {0};
					timeinfo.tm_year = atoi(lv_textarea_get_text(ui_yeartextarea)) - 1900;
					timeinfo.tm_mon = atoi(lv_textarea_get_text(ui_monthtextarea)) - 1;
					timeinfo.tm_mday = atoi(lv_textarea_get_text(ui_daytextarea));
					timeinfo.tm_hour = atoi(lv_textarea_get_text(ui_hourtextarea));
					timeinfo.tm_min = atoi(lv_textarea_get_text(ui_mintextarea));
					timeinfo.tm_sec = atoi(lv_textarea_get_text(ui_secondtextarea));
					time_t ts = timegm(&timeinfo) - 28800u;
					set_timestamp(ts);
				}
				memcpy(settings.pass,lv_textarea_get_text(ui_passtextarea),4);
				save_settings_req = 1;
				settings_upload_req = 1;
			}
			else if((ui_Keyboard5 == obj)&&(id == 7))
			{
				rt_kprintf("kb5 ok pressed\n");
				settings.bl_percent = atoi(lv_textarea_get_text(ui_backlighttextarea2));
				if(settings.bl_percent < 5)
					settings.bl_percent = 5;
				else if(settings.bl_percent > 100)
					settings.bl_percent = 100;
				sprintf(str, "%d", settings.bl_percent);
				lv_textarea_set_text(ui_backlighttextarea2, str);
				
				set_lcd_backlight_percent(settings.bl_percent);
				
				settings.idle = atoi(lv_textarea_get_text(ui_passtextarea2));
				if(settings.idle < 5)
					settings.idle = 5;
				else if(settings.idle > 3600)
					settings.idle = 3600;
				sprintf(str, "%d", settings.idle);
				lv_textarea_set_text(ui_passtextarea2, str);
				save_settings_req = 1;
			}
			else if((ui_Keyboard6 == obj)&&(id == 7))
			{
				rt_kprintf("kb6 ok pressed\n");
				lv_event_send(ui_Button1, LV_EVENT_CLICKED, NULL);
			}
			else if((ui_Keyboard8 == obj)&&(id == 7))
			{
				rt_kprintf("kb8 ok pressed\n");
				settings.pt = atoi(lv_textarea_get_text(ui_pttextarea));
				if(settings.pt < 1)
					settings.pt = 1;
				else if(settings.pt >1000)
					settings.pt = 1000;
				sprintf(str, "%d", settings.pt);
				lv_textarea_set_text(ui_pttextarea, str);
				
				settings.ct = atoi(lv_textarea_get_text(ui_cttextarea));
				if(settings.ct < 1)
					settings.ct = 1;
				else if(settings.ct >1000)
					settings.ct = 1000;
				sprintf(str, "%d", settings.ct);
				lv_textarea_set_text(ui_cttextarea, str);
				
				settings.i0_limt = atof(lv_textarea_get_text(ui_i0overtextarea));
				if(settings.i0_limt < 1.0f)
					settings.i0_limt = 1.0f;
				else if(settings.i0_limt >1000.0f)
					settings.i0_limt = 1000.0f;
				sprintf(str, "%.2f", settings.i0_limt);
				lv_textarea_set_text(ui_i0overtextarea, str);
				
				settings.i0_ct = atoi(lv_textarea_get_text(ui_i0overtextarea2));
				if(settings.i0_ct < 1)
					settings.i0_ct = 1;
				else if(settings.i0_ct >1000)
					settings.i0_ct = 1000;
				sprintf(str, "%d", settings.i0_ct);
				lv_textarea_set_text(ui_i0overtextarea2, str);
				save_settings_req = 1;
				save_ptct_req = 1;
				settings_upload_req = 1;
			}
			else if(((ui_Keyboard10 == obj)&&(id == 7))||((ui_Keyboard11 == obj)&&(id == 7)))
			{
				rt_kprintf("kb10 ok pressed\n");
				settings.rs485_id = atoi(lv_textarea_get_text(ui_TextArea7));
				if(settings.rs485_id < 1)
					settings.rs485_id = 1;
				else if(settings.rs485_id >255)
					settings.rs485_id = 255;
				sprintf(str, "%d", settings.rs485_id);
				lv_textarea_set_text(ui_TextArea7, str);
				
				if(lv_dropdown_get_selected(ui_Dropdown1) == 0)
					settings.rs485_baud = 1200;
				else if(lv_dropdown_get_selected(ui_Dropdown1) == 1)
					settings.rs485_baud = 2400;
				else if(lv_dropdown_get_selected(ui_Dropdown1) == 2)
					settings.rs485_baud = 4800;
				else if(lv_dropdown_get_selected(ui_Dropdown1) == 3)
					settings.rs485_baud = 9600;
				
				sprintf(settings.server_addr, "%s", lv_textarea_get_text(ui_TextArea9));
				settings.server_port = atoi(lv_textarea_get_text(ui_TextArea8));
				
				if(lv_obj_has_state(ui_Checkbox2, LV_STATE_CHECKED))
				{
					//ethernet
					settings.use4g = 0;
					
					//TextArea10
				}
				else if(lv_obj_has_state(ui_Checkbox1, LV_STATE_CHECKED))
				{
					//4g
					settings.use4g = 1;
				}
				
				//TextArea10	//mac
				sprintf(settings.mac, "%s", lv_textarea_get_text(ui_TextArea10));
				//TextArea11	//ip
				sprintf(settings.self_addr, "%s", lv_textarea_get_text(ui_TextArea11));
				//TextArea12	//mask
				sprintf(settings.netmask, "%s", lv_textarea_get_text(ui_TextArea12));
				//TextArea13	//gw
				sprintf(settings.gw, "%s", lv_textarea_get_text(ui_TextArea13));
				
				save_settings_req = 1;
				save_request_reset = 1;
			}
			else
				rt_kprintf("%s %d was pressed\n", txt, id);
	}
}

void checkpassword(lv_event_t * e)
{
	// Your code here
	if(0 == strcasecmp((char *)settings.pass, lv_textarea_get_text(ui_pttextarea2)))
		lv_obj_add_flag(ui_paddialog, LV_OBJ_FLAG_HIDDEN);
}

void touchrecalc(lv_event_t * e)
{
	// Your code here
	nvs_clear_coeff();
}
void popconform(lv_event_t * e)
{
	// Your code here
	lv_tabview_set_act(ui_TabView1, 2, LV_ANIM_OFF);
	lv_obj_add_flag(ui_dialog, LV_OBJ_FLAG_HIDDEN);
	line_error = 0;
	line_gnd = 0;
}
void preparecal(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	cmd_calc_prepare_req = 1;
}

void dovoltagecal(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	cmd_calc_v_done_req = 1;
}

void docurrentcal(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	cmd_calc_c_done_req = 1;
}
void out1clicked(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	if(calc_status.out_status&0x01)
	{
		relay_op_req = 0x10;
	}
	else
	{
		relay_op_req = 0x11;
	}
}

void out4clicked(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	if(calc_status.out_status&0x08)
	{
		relay_op_req = 0x40;
	}
	else
	{
		relay_op_req = 0x41;
	}
}

void out3clicked(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	if(calc_status.out_status&0x04)
	{
		relay_op_req = 0x30;
	}
	else
	{
		relay_op_req = 0x31;
	}
}

void out2clicked(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	if(calc_status.out_status&0x02)
	{
		relay_op_req = 0x20;
	}
	else
	{
		relay_op_req = 0x21;
	}
}

void out5clicked(lv_event_t * e)
{
	// Your code here
	if(calc_status.in_status & 0x01)
		return;
	if(calc_status.out_status&0x10)
	{
		relay_op_req = 0x50;
	}
	else
	{
		relay_op_req = 0x51;
	}
}
void errorreset(lv_event_t * e)
{
	// Your code here
	last_error_is_perm = 0;
	perm_error_clr_req = 1;
}
void scrmainloaded(lv_event_t * e)
{
	// Your code here
	nodelist_table[0][0] = ui_Label106;
	nodelist_table[0][1] = ui_Label98;
	nodelist_table[0][2] = ui_Label103;
	nodelist_table[0][3] = ui_Label104;
	
	nodelist_table[1][0] = ui_Label110;
	nodelist_table[1][1] = ui_Label105;
	nodelist_table[1][2] = ui_Label107;
	nodelist_table[1][3] = ui_Label108;
	
	nodelist_table[2][0] = ui_Label114;
	nodelist_table[2][1] = ui_Label109;
	nodelist_table[2][2] = ui_Label111;
	nodelist_table[2][3] = ui_Label112;
	
	nodelist_table[3][0] = ui_Label115;
	nodelist_table[3][1] = ui_Label116;
	nodelist_table[3][2] = ui_Label117;
	nodelist_table[3][3] = ui_Label118;
	
	nodelist_table[4][0] = ui_Label119;
	nodelist_table[4][1] = ui_Label120;
	nodelist_table[4][2] = ui_Label121;
	nodelist_table[4][3] = ui_Label122;
	
	nodelist_table[5][0] = ui_Label123;
	nodelist_table[5][1] = ui_Label124;
	nodelist_table[5][2] = ui_Label125;
	nodelist_table[5][3] = ui_Label126;
	
	nodelist_table[6][0] = ui_Label127;
	nodelist_table[6][1] = ui_Label128;
	nodelist_table[6][2] = ui_Label129;
	nodelist_table[6][3] = ui_Label130;
	
	nodelist_table[7][0] = ui_Label131;
	nodelist_table[7][1] = ui_Label132;
	nodelist_table[7][2] = ui_Label133;
	nodelist_table[7][3] = ui_Label134;
	
	disp_node_page_idx = 1;
	disp_node_page_cnt = 1;
}
void nodelistnext(lv_event_t * e)
{
	// Your code here
	if(disp_node_page_idx < disp_node_page_cnt)
	{
		disp_node_page_idx++;
		disp_node_page_update = 1;
	}
}

void nodelistprev(lv_event_t * e)
{
	// Your code here
	if(disp_node_page_idx>1)
	{
		disp_node_page_idx--;
		disp_node_page_update = 1;
	}
}
void popcancel(lv_event_t * e)
{
	// Your code here
	line_error = 0;
	line_gnd = 0;
}
uint8_t old_tab_idx = 0;
void errorpagechanged(lv_event_t * e)
{
	// Your code here
	uint8_t tab_idx = lv_tabview_get_tab_act(ui_TabView3);
	if(old_tab_idx != tab_idx)
	{
		old_tab_idx = tab_idx;
		switch(tab_idx)
		{
			case 0:
				over_error_wave_load = 1;
				while(over_error_wave_load == 1)
					rt_thread_mdelay(1);
				break;
			case 1:
				gnd_error_wave_load = 1;
				while(gnd_error_wave_load == 1)
					rt_thread_mdelay(1);
				break;
			case 2:
				drop_error_wave_load = 1;
				while(drop_error_wave_load == 1)
					rt_thread_mdelay(1);
				break;
			case 3:
				pt_error_wave_load = 1;
				while(pt_error_wave_load == 1)
					rt_thread_mdelay(1);
				break;
			case 4:
				short_error_wave_load = 1;
				while(short_error_wave_load == 1)
					rt_thread_mdelay(1);
				break;
		}
	}
}
void overerrornext(lv_event_t * e)
{
	// Your code here
	if(over_error_cnt >0)
	{
		if(over_error_idx < (over_error_cnt - 1))
		{
			over_error_idx+=1;
			over_error_wave_load = 1;
			while(over_error_wave_load == 1)
					rt_thread_mdelay(1);
		}
	}
}

void overerrorprev(lv_event_t * e)
{
	// Your code here
	if(over_error_idx > 0)
	{
		over_error_idx-=1;
		over_error_wave_load = 1;
		while(over_error_wave_load == 1)
				rt_thread_mdelay(1);
	}
}

void gnderrornext(lv_event_t * e)
{
	// Your code here
	if(gnd_error_cnt >0)
	{
		if(gnd_error_idx < (gnd_error_cnt - 1))
		{
			gnd_error_idx+=1;
			gnd_error_wave_load = 1;
			while(gnd_error_wave_load == 1)
					rt_thread_mdelay(1);
		}
	}
}

void gnderrorprev(lv_event_t * e)
{
	// Your code here
	if(gnd_error_idx > 0)
	{
		gnd_error_idx-=1;
		gnd_error_wave_load = 1;
		while(gnd_error_wave_load == 1)
				rt_thread_mdelay(1);
	}
}

void droperrornext(lv_event_t * e)
{
	// Your code here
	if(drop_error_cnt >0)
	{
		if(drop_error_idx < (drop_error_cnt - 1))
		{
			drop_error_idx+=1;
			drop_error_wave_load = 1;
			while(drop_error_wave_load == 1)
					rt_thread_mdelay(1);
		}
	}
}

void droperrorprev(lv_event_t * e)
{
	// Your code here
	if(drop_error_idx > 0)
	{
		drop_error_idx-=1;
		drop_error_wave_load = 1;
		while(drop_error_wave_load == 1)
				rt_thread_mdelay(1);
	}
}

void pterrornext(lv_event_t * e)
{
	// Your code here
	if(pt_error_cnt >0)
	{
		if(pt_error_idx < (pt_error_cnt - 1))
		{
			pt_error_idx+=1;
			pt_error_wave_load = 1;
			while(pt_error_wave_load == 1)
					rt_thread_mdelay(1);
		}
	}
}

void pterrorprev(lv_event_t * e)
{
	// Your code here
	if(pt_error_idx > 0)
	{
		pt_error_idx-=1;
		pt_error_wave_load = 1;
		while(pt_error_wave_load == 1)
				rt_thread_mdelay(1);
	}
}

void shorterrornext(lv_event_t * e)
{
	// Your code here
	if(short_error_cnt >0)
	{
		if(short_error_idx < (short_error_cnt - 1))
		{
			short_error_idx+=1;
			short_error_wave_load = 1;
			while(short_error_wave_load == 1)
					rt_thread_mdelay(1);
		}
	}
}

void shorterrorprev(lv_event_t * e)
{
	// Your code here
	if(short_error_idx > 0)
	{
		short_error_idx-=1;
		short_error_wave_load = 1;
		while(short_error_wave_load == 1)
				rt_thread_mdelay(1);
	}
}
void timechanged(lv_event_t * e)
{
	// Your code here
	time_setting_changed = 1;
}

void settingstabchanged(lv_event_t * e)
{
	// Your code here
	uint8_t main_tab_idx = lv_tabview_get_tab_act(ui_TabView1);
	uint8_t tab_idx = lv_tabview_get_tab_act(ui_TabView2);
	if((tab_idx == 0)&&(main_tab_idx == 1))
		time_settings_auto_update = 0;
	else
	{
		time_setting_changed = 0;
		time_settings_auto_update = 1;
	}
}

